### PR TITLE
Feature authentication

### PR DESCRIPTION
**Pull request by WebDevJL**

### CODE REVIEW

**Comment by WebDevJL** [comment]
@damirius Can you solve the conflicts please? Thanks.

**Comment by WebDevJL** [comment]
@damirius and fix the build? Thanks 👍

**Comment by damirius** [comment]
@WebDevJL 

This was rather interesting to fix. For some reason running `php bin/console doctrine:database:create --env=test` showed an error that database doesn't exist even when this command is used for creating the db, so I have no clue what's up with that. Also `cache:clear` was trying to work with default db which wasn't setup. So it was really weird. Now travis is setup for testing, but there is some problem with authenticating users through the login. I'll see whats up with that, maybe we must generate private and public keys there instead of using ones shared in the repo.

**Comment by damirius** [comment]
@WebDevJL 

I think this should be resolved and merged, I think everything will work OK. Please do tell me if I missed something

**Pull request merged**
